[build]
  command = """
    mkdir -p dist && 
    cp index.html dist/ && 
    cp -r AB dist/ &&
    cp -r audiodata dist/ &&
    cp -r meter dist/ &&
    cp -r mixer dist/ &&
    cp -r tuner dist/ &&
    cp main.js dist/ &&
    cp preload.js dist/ &&
    cd src/audio2text && 
    npm install && 
    npm run build && 
    echo "Contents of .next directory:" &&
    ls -la .next &&
    echo "\nContents of .next/standalone:" &&
    ls -la .next/standalone &&
    mkdir -p ../../dist/audio2text/_next/static && 
    cp -r .next/standalone/* ../../dist/audio2text/ && 
    cp -r .next/static/* ../../dist/audio2text/_next/static/ &&
    echo "\nFinal contents of dist/audio2text:" &&
    cd ../../dist/audio2text &&
    ls -la
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "/.netlify/functions"

[[redirects]]
  from = "/audio2text/_next/*"
  to = "/audio2text/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/audio2text/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/audio2text"
  to = "/audio2text/index.html"
  status = 200

[[redirects]]
  from = "/audio2text/*"
  to = "/audio2text/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = ["/"]}
