[build]
  command = "cp index.html dist/ && cd src/audio2text && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/audio2text/*"
  to = "/audio2text/_next/:splat"
  status = 200

[[redirects]]
  from = "/audio2text/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
