[build]
  base = "src/audio2text"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/audio2text/*"
  to = "/audio2text/_next/:splat"
  status = 200

[[redirects]]
  from = "/audio2text/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/audio2text"
  status = 301
