[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/audio2text/_next/*"
  to = "/audio2text/.next/:splat"
  status = 200

[[redirects]]
  from = "/audio2text/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/audio2text"
  to = "/audio2text/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
