[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/audio2text/*"
  to = "/audio2text/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/audio2text"
  status = 302
