[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/audio2text/*"
  to = "/audio2text/index.html"
  status = 200

[[redirects]]
  from = "/audio2text"
  to = "/audio2text/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
