[build]
  command = """
    mkdir -p dist && 
    cp index.html dist/ && 
    cp -r AB dist/ &&
    cp -r audiodata dist/ &&
    cp -r meter dist/ &&
    cp -r mixer dist/ &&
    cp -r tuner dist/ &&
    cp main.js dist/ &&
    cp preload.js dist/ &&
    cd src/audio2text && 
    npm install && 
    npm run build && 
    echo "Contents of out directory:" &&
    ls -la out &&
    cp -r out/* ../../dist/audio2text/
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "/.netlify/functions"

[[redirects]]
  from = "/audio2text/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = ["/"]}
