[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
